#############################################################################
# Makefile for building: Handi
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  Handi.pro
# Template: app
# Command: /home/nathan/raspi/qt5/bin/qmake -o Makefile Handi.pro -spec devices/linux-rasp-pi3-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc
CXX           = /home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/home/nathan/raspi/sysroot -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/home/nathan/raspi/sysroot -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../raspi/qt5pi/include -I../../raspi/qt5pi/include/QtWidgets -I../../raspi/qt5pi/include/QtGui -I../../raspi/qt5pi/include/QtSerialPort -I../../raspi/qt5pi/include/QtSql -I../../raspi/qt5pi/include/QtCore -I. -I=/opt/vc/include -I=/opt/vc/include/interface/vcos/pthreads -I=/opt/vc/include/interface/vmcs_host/linux -I../../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++
QMAKE         = /home/nathan/raspi/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/nathan/raspi/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/nathan/raspi/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Handi1.0.0
DISTDIR = /home/nathan/Handi/HandiDom/.tmp/Handi1.0.0
LINK          = /home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
LFLAGS        = -mfloat-abi=hard --sysroot=/home/nathan/raspi/sysroot -Wl,-rpath,/usr/local/qt5pi/lib -Wl,-rpath-link,/home/nathan/raspi/sysroot/opt/vc/lib -Wl,-rpath-link,/home/nathan/raspi/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/home/nathan/raspi/sysroot/lib/arm-linux-gnueabihf
LIBS          = $(SUBLIBS) -L=/opt/vc/lib -L/home/nathan/raspi/qt5pi/lib -lQt5Widgets -lQt5Gui -lQt5SerialPort -lQt5Sql -lQt5Core -L/home/nathan/raspi/sysroot/usr/lib/arm-linux-gnueabihf -lGLESv2 -lpthread 
AR            = /home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = frame.cpp \
		contact.cpp \
		main.cpp \
		communication.cpp moc_frame.cpp
OBJECTS       = frame.o \
		contact.o \
		main.o \
		communication.o \
		moc_frame.o
DIST          = ../../raspi/qt5/mkspecs/features/spec_pre.prf \
		../../raspi/qt5/mkspecs/common/unix.conf \
		../../raspi/qt5/mkspecs/common/linux.conf \
		../../raspi/qt5/mkspecs/common/sanitize.conf \
		../../raspi/qt5/mkspecs/common/gcc-base.conf \
		../../raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		../../raspi/qt5/mkspecs/common/g++-base.conf \
		../../raspi/qt5/mkspecs/common/g++-unix.conf \
		../../raspi/qt5/mkspecs/qdevice.pri \
		../../raspi/qt5/mkspecs/features/device_config.prf \
		../../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		../../raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		../../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		../../raspi/qt5/mkspecs/qconfig.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../../raspi/qt5/mkspecs/features/qt_functions.prf \
		../../raspi/qt5/mkspecs/features/qt_config.prf \
		../../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf \
		../../raspi/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../raspi/qt5/mkspecs/features/exclusive_builds.prf \
		../../raspi/qt5/mkspecs/features/toolchain.prf \
		../../raspi/qt5/mkspecs/features/default_pre.prf \
		../../raspi/qt5/mkspecs/features/resolve_config.prf \
		../../raspi/qt5/mkspecs/features/default_post.prf \
		../../raspi/qt5/mkspecs/features/qml_debug.prf \
		../../raspi/qt5/mkspecs/features/warn_on.prf \
		../../raspi/qt5/mkspecs/features/qt.prf \
		../../raspi/qt5/mkspecs/features/resources.prf \
		../../raspi/qt5/mkspecs/features/moc.prf \
		../../raspi/qt5/mkspecs/features/unix/opengl.prf \
		../../raspi/qt5/mkspecs/features/uic.prf \
		../../raspi/qt5/mkspecs/features/unix/thread.prf \
		../../raspi/qt5/mkspecs/features/qmake_use.prf \
		../../raspi/qt5/mkspecs/features/file_copies.prf \
		../../raspi/qt5/mkspecs/features/testcase_targets.prf \
		../../raspi/qt5/mkspecs/features/exceptions.prf \
		../../raspi/qt5/mkspecs/features/yacc.prf \
		../../raspi/qt5/mkspecs/features/lex.prf \
		Handi.pro contact.h \
		frame.h \
		communication.h frame.cpp \
		contact.cpp \
		main.cpp \
		communication.cpp
QMAKE_TARGET  = Handi
DESTDIR       = 
TARGET        = Handi


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Handi.pro ../../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf ../../raspi/qt5/mkspecs/features/spec_pre.prf \
		../../raspi/qt5/mkspecs/common/unix.conf \
		../../raspi/qt5/mkspecs/common/linux.conf \
		../../raspi/qt5/mkspecs/common/sanitize.conf \
		../../raspi/qt5/mkspecs/common/gcc-base.conf \
		../../raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		../../raspi/qt5/mkspecs/common/g++-base.conf \
		../../raspi/qt5/mkspecs/common/g++-unix.conf \
		../../raspi/qt5/mkspecs/qdevice.pri \
		../../raspi/qt5/mkspecs/features/device_config.prf \
		../../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		../../raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		../../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		../../raspi/qt5/mkspecs/qconfig.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../../raspi/qt5/mkspecs/features/qt_functions.prf \
		../../raspi/qt5/mkspecs/features/qt_config.prf \
		../../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf \
		../../raspi/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../raspi/qt5/mkspecs/features/exclusive_builds.prf \
		../../raspi/qt5/mkspecs/features/toolchain.prf \
		../../raspi/qt5/mkspecs/features/default_pre.prf \
		../../raspi/qt5/mkspecs/features/resolve_config.prf \
		../../raspi/qt5/mkspecs/features/default_post.prf \
		../../raspi/qt5/mkspecs/features/qml_debug.prf \
		../../raspi/qt5/mkspecs/features/warn_on.prf \
		../../raspi/qt5/mkspecs/features/qt.prf \
		../../raspi/qt5/mkspecs/features/resources.prf \
		../../raspi/qt5/mkspecs/features/moc.prf \
		../../raspi/qt5/mkspecs/features/unix/opengl.prf \
		../../raspi/qt5/mkspecs/features/uic.prf \
		../../raspi/qt5/mkspecs/features/unix/thread.prf \
		../../raspi/qt5/mkspecs/features/qmake_use.prf \
		../../raspi/qt5/mkspecs/features/file_copies.prf \
		../../raspi/qt5/mkspecs/features/testcase_targets.prf \
		../../raspi/qt5/mkspecs/features/exceptions.prf \
		../../raspi/qt5/mkspecs/features/yacc.prf \
		../../raspi/qt5/mkspecs/features/lex.prf \
		Handi.pro \
		../../raspi/qt5pi/lib/libQt5Widgets.prl \
		../../raspi/qt5pi/lib/libQt5Gui.prl \
		../../raspi/qt5pi/lib/libQt5SerialPort.prl \
		../../raspi/qt5pi/lib/libQt5Sql.prl \
		../../raspi/qt5pi/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Handi.pro -spec devices/linux-rasp-pi3-g++ CONFIG+=debug CONFIG+=qml_debug
../../raspi/qt5/mkspecs/features/spec_pre.prf:
../../raspi/qt5/mkspecs/common/unix.conf:
../../raspi/qt5/mkspecs/common/linux.conf:
../../raspi/qt5/mkspecs/common/sanitize.conf:
../../raspi/qt5/mkspecs/common/gcc-base.conf:
../../raspi/qt5/mkspecs/common/gcc-base-unix.conf:
../../raspi/qt5/mkspecs/common/g++-base.conf:
../../raspi/qt5/mkspecs/common/g++-unix.conf:
../../raspi/qt5/mkspecs/qdevice.pri:
../../raspi/qt5/mkspecs/features/device_config.prf:
../../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf:
../../raspi/qt5/mkspecs/devices/common/linux_device_post.conf:
../../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf:
../../raspi/qt5/mkspecs/qconfig.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_core.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_gui.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_network.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_serialport.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_sql.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_xml.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
../../raspi/qt5/mkspecs/features/qt_functions.prf:
../../raspi/qt5/mkspecs/features/qt_config.prf:
../../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf:
../../raspi/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
../../raspi/qt5/mkspecs/features/exclusive_builds.prf:
../../raspi/qt5/mkspecs/features/toolchain.prf:
../../raspi/qt5/mkspecs/features/default_pre.prf:
../../raspi/qt5/mkspecs/features/resolve_config.prf:
../../raspi/qt5/mkspecs/features/default_post.prf:
../../raspi/qt5/mkspecs/features/qml_debug.prf:
../../raspi/qt5/mkspecs/features/warn_on.prf:
../../raspi/qt5/mkspecs/features/qt.prf:
../../raspi/qt5/mkspecs/features/resources.prf:
../../raspi/qt5/mkspecs/features/moc.prf:
../../raspi/qt5/mkspecs/features/unix/opengl.prf:
../../raspi/qt5/mkspecs/features/uic.prf:
../../raspi/qt5/mkspecs/features/unix/thread.prf:
../../raspi/qt5/mkspecs/features/qmake_use.prf:
../../raspi/qt5/mkspecs/features/file_copies.prf:
../../raspi/qt5/mkspecs/features/testcase_targets.prf:
../../raspi/qt5/mkspecs/features/exceptions.prf:
../../raspi/qt5/mkspecs/features/yacc.prf:
../../raspi/qt5/mkspecs/features/lex.prf:
Handi.pro:
../../raspi/qt5pi/lib/libQt5Widgets.prl:
../../raspi/qt5pi/lib/libQt5Gui.prl:
../../raspi/qt5pi/lib/libQt5SerialPort.prl:
../../raspi/qt5pi/lib/libQt5Sql.prl:
../../raspi/qt5pi/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Handi.pro -spec devices/linux-rasp-pi3-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../raspi/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents contact.h frame.h communication.h $(DISTDIR)/
	$(COPY_FILE) --parents frame.cpp contact.cpp main.cpp communication.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../raspi/qt5/mkspecs/features/data/dummy.cpp
	/home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++ -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/home/nathan/raspi/sysroot -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../raspi/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_frame.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_frame.cpp
moc_frame.cpp: ../../raspi/qt5pi/include/QtWidgets/QMainWindow \
		../../raspi/qt5pi/include/QtWidgets/qmainwindow.h \
		../../raspi/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../raspi/qt5pi/include/QtCore/qflags.h \
		../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../../raspi/qt5pi/include/QtWidgets/qtwidgets-config.h \
		../../raspi/qt5pi/include/QtWidgets/qwidget.h \
		../../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../../raspi/qt5pi/include/QtCore/qobject.h \
		../../raspi/qt5pi/include/QtCore/qstring.h \
		../../raspi/qt5pi/include/QtCore/qchar.h \
		../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qstringview.h \
		../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../raspi/qt5pi/include/QtCore/qlist.h \
		../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../raspi/qt5pi/include/QtCore/qpair.h \
		../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../raspi/qt5pi/include/QtCore/qmargins.h \
		../../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../../raspi/qt5pi/include/QtCore/qrect.h \
		../../raspi/qt5pi/include/QtCore/qsize.h \
		../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../raspi/qt5pi/include/QtGui/qpalette.h \
		../../raspi/qt5pi/include/QtGui/qcolor.h \
		../../raspi/qt5pi/include/QtGui/qrgb.h \
		../../raspi/qt5pi/include/QtGui/qrgba64.h \
		../../raspi/qt5pi/include/QtGui/qbrush.h \
		../../raspi/qt5pi/include/QtCore/qvector.h \
		../../raspi/qt5pi/include/QtGui/qmatrix.h \
		../../raspi/qt5pi/include/QtGui/qpolygon.h \
		../../raspi/qt5pi/include/QtGui/qregion.h \
		../../raspi/qt5pi/include/QtCore/qdatastream.h \
		../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../raspi/qt5pi/include/QtCore/qline.h \
		../../raspi/qt5pi/include/QtGui/qtransform.h \
		../../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../../raspi/qt5pi/include/QtGui/qimage.h \
		../../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../../raspi/qt5pi/include/QtGui/qpixmap.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../raspi/qt5pi/include/QtCore/qhash.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../raspi/qt5pi/include/QtGui/qfont.h \
		../../raspi/qt5pi/include/QtGui/qfontmetrics.h \
		../../raspi/qt5pi/include/QtGui/qfontinfo.h \
		../../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../../raspi/qt5pi/include/QtGui/qcursor.h \
		../../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../../raspi/qt5pi/include/QtGui/qevent.h \
		../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../raspi/qt5pi/include/QtCore/qmap.h \
		../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../raspi/qt5pi/include/QtCore/qset.h \
		../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../raspi/qt5pi/include/QtCore/qurl.h \
		../../raspi/qt5pi/include/QtCore/qurlquery.h \
		../../raspi/qt5pi/include/QtCore/qfile.h \
		../../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../../raspi/qt5pi/include/QtGui/qvector2d.h \
		../../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../../raspi/qt5pi/include/QtWidgets/qtabwidget.h \
		../../raspi/qt5pi/include/QtGui/qicon.h \
		../../raspi/qt5pi/include/QtWidgets/QGridLayout \
		../../raspi/qt5pi/include/QtWidgets/qgridlayout.h \
		../../raspi/qt5pi/include/QtWidgets/qlayout.h \
		../../raspi/qt5pi/include/QtWidgets/qlayoutitem.h \
		../../raspi/qt5pi/include/QtWidgets/qboxlayout.h \
		../../raspi/qt5pi/include/QtCore/QMapIterator \
		contact.h \
		../../raspi/qt5pi/include/QtCore/QObject \
		../../raspi/qt5pi/include/QtCore/QString \
		frame.h \
		moc_predefs.h \
		../../raspi/qt5/bin/moc
	/home/nathan/raspi/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/nathan/raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++ -I/home/nathan/Handi/HandiDom -I/home/nathan/raspi/qt5pi/include -I/home/nathan/raspi/qt5pi/include/QtWidgets -I/home/nathan/raspi/qt5pi/include/QtGui -I/home/nathan/raspi/qt5pi/include/QtSerialPort -I/home/nathan/raspi/qt5pi/include/QtSql -I/home/nathan/raspi/qt5pi/include/QtCore -I/home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3 -I/home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include -I/home/nathan/raspi/sysroot/usr/include -I/home/nathan/raspi/sysroot/usr/include/arm-linux-gnueabihf frame.h -o moc_frame.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

frame.o: frame.cpp ../../raspi/qt5pi/include/QtWidgets/QApplication \
		../../raspi/qt5pi/include/QtWidgets/qapplication.h \
		../../raspi/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../raspi/qt5pi/include/QtCore/qflags.h \
		../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../../raspi/qt5pi/include/QtWidgets/qtwidgets-config.h \
		../../raspi/qt5pi/include/QtCore/qcoreapplication.h \
		../../raspi/qt5pi/include/QtCore/qstring.h \
		../../raspi/qt5pi/include/QtCore/qchar.h \
		../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qstringview.h \
		../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../raspi/qt5pi/include/QtCore/qobject.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../raspi/qt5pi/include/QtCore/qlist.h \
		../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../raspi/qt5pi/include/QtCore/qpair.h \
		../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../raspi/qt5pi/include/QtCore/qeventloop.h \
		../../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../raspi/qt5pi/include/QtCore/qsize.h \
		../../raspi/qt5pi/include/QtGui/qcursor.h \
		../../raspi/qt5pi/include/QtWidgets/qdesktopwidget.h \
		../../raspi/qt5pi/include/QtWidgets/qwidget.h \
		../../raspi/qt5pi/include/QtCore/qmargins.h \
		../../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../../raspi/qt5pi/include/QtCore/qrect.h \
		../../raspi/qt5pi/include/QtGui/qpalette.h \
		../../raspi/qt5pi/include/QtGui/qcolor.h \
		../../raspi/qt5pi/include/QtGui/qrgb.h \
		../../raspi/qt5pi/include/QtGui/qrgba64.h \
		../../raspi/qt5pi/include/QtGui/qbrush.h \
		../../raspi/qt5pi/include/QtCore/qvector.h \
		../../raspi/qt5pi/include/QtGui/qmatrix.h \
		../../raspi/qt5pi/include/QtGui/qpolygon.h \
		../../raspi/qt5pi/include/QtGui/qregion.h \
		../../raspi/qt5pi/include/QtCore/qdatastream.h \
		../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../raspi/qt5pi/include/QtCore/qline.h \
		../../raspi/qt5pi/include/QtGui/qtransform.h \
		../../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../../raspi/qt5pi/include/QtGui/qimage.h \
		../../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../../raspi/qt5pi/include/QtGui/qpixmap.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../raspi/qt5pi/include/QtCore/qhash.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../raspi/qt5pi/include/QtGui/qfont.h \
		../../raspi/qt5pi/include/QtGui/qfontmetrics.h \
		../../raspi/qt5pi/include/QtGui/qfontinfo.h \
		../../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../../raspi/qt5pi/include/QtGui/qevent.h \
		../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../raspi/qt5pi/include/QtCore/qmap.h \
		../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../raspi/qt5pi/include/QtCore/qset.h \
		../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../raspi/qt5pi/include/QtCore/qurl.h \
		../../raspi/qt5pi/include/QtCore/qurlquery.h \
		../../raspi/qt5pi/include/QtCore/qfile.h \
		../../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../../raspi/qt5pi/include/QtGui/qvector2d.h \
		../../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../../raspi/qt5pi/include/QtGui/qguiapplication.h \
		../../raspi/qt5pi/include/QtGui/qinputmethod.h \
		../../raspi/qt5pi/include/QtWidgets/QPushButton \
		../../raspi/qt5pi/include/QtWidgets/qpushbutton.h \
		../../raspi/qt5pi/include/QtWidgets/qabstractbutton.h \
		../../raspi/qt5pi/include/QtGui/qicon.h \
		../../raspi/qt5pi/include/QtWidgets/QStyle \
		../../raspi/qt5pi/include/QtWidgets/qstyle.h \
		../../raspi/qt5pi/include/QtWidgets/QDesktopWidget \
		../../raspi/qt5pi/include/QtCore/QProcess \
		../../raspi/qt5pi/include/QtCore/qprocess.h \
		contact.h \
		../../raspi/qt5pi/include/QtCore/QObject \
		../../raspi/qt5pi/include/QtCore/QString \
		frame.h \
		../../raspi/qt5pi/include/QtWidgets/QMainWindow \
		../../raspi/qt5pi/include/QtWidgets/qmainwindow.h \
		../../raspi/qt5pi/include/QtWidgets/qtabwidget.h \
		../../raspi/qt5pi/include/QtWidgets/QGridLayout \
		../../raspi/qt5pi/include/QtWidgets/qgridlayout.h \
		../../raspi/qt5pi/include/QtWidgets/qlayout.h \
		../../raspi/qt5pi/include/QtWidgets/qlayoutitem.h \
		../../raspi/qt5pi/include/QtWidgets/qboxlayout.h \
		../../raspi/qt5pi/include/QtCore/QMapIterator \
		../../raspi/qt5pi/include/QtCore/QMap \
		../../raspi/qt5pi/include/QtCore/QDebug \
		../../raspi/qt5pi/include/QtWidgets/QWidget \
		../../raspi/qt5pi/include/QtGui/QCloseEvent \
		../../raspi/qt5pi/include/QtWidgets/QMessageBox \
		../../raspi/qt5pi/include/QtWidgets/qmessagebox.h \
		../../raspi/qt5pi/include/QtWidgets/qdialog.h \
		../../raspi/qt5pi/include/QtWidgets/QLabel \
		../../raspi/qt5pi/include/QtWidgets/qlabel.h \
		../../raspi/qt5pi/include/QtWidgets/qframe.h \
		../../raspi/qt5pi/include/QtSql/QtSql \
		../../raspi/qt5pi/include/QtSql/QtSqlDepends \
		../../raspi/qt5pi/include/QtCore/QtCore \
		../../raspi/qt5pi/include/QtCore/QtCoreDepends \
		../../raspi/qt5pi/include/QtCore/qabstractanimation.h \
		../../raspi/qt5pi/include/QtCore/qabstracteventdispatcher.h \
		../../raspi/qt5pi/include/QtCore/qabstractitemmodel.h \
		../../raspi/qt5pi/include/QtCore/qabstractnativeeventfilter.h \
		../../raspi/qt5pi/include/QtCore/qabstractproxymodel.h \
		../../raspi/qt5pi/include/QtCore/qabstractstate.h \
		../../raspi/qt5pi/include/QtCore/qabstracttransition.h \
		../../raspi/qt5pi/include/QtCore/qanimationgroup.h \
		../../raspi/qt5pi/include/QtCore/qarraydataops.h \
		../../raspi/qt5pi/include/QtCore/qarraydatapointer.h \
		../../raspi/qt5pi/include/QtCore/qbasictimer.h \
		../../raspi/qt5pi/include/QtCore/qbitarray.h \
		../../raspi/qt5pi/include/QtCore/qbuffer.h \
		../../raspi/qt5pi/include/QtCore/qbytearraymatcher.h \
		../../raspi/qt5pi/include/QtCore/qcache.h \
		../../raspi/qt5pi/include/QtCore/qcollator.h \
		../../raspi/qt5pi/include/QtCore/qcommandlineoption.h \
		../../raspi/qt5pi/include/QtCore/qcommandlineparser.h \
		../../raspi/qt5pi/include/QtCore/qcryptographichash.h \
		../../raspi/qt5pi/include/QtCore/qdatetime.h \
		../../raspi/qt5pi/include/QtCore/qdeadlinetimer.h \
		../../raspi/qt5pi/include/QtCore/qelapsedtimer.h \
		../../raspi/qt5pi/include/QtCore/qdir.h \
		../../raspi/qt5pi/include/QtCore/qfileinfo.h \
		../../raspi/qt5pi/include/QtCore/qdiriterator.h \
		../../raspi/qt5pi/include/QtCore/qeasingcurve.h \
		../../raspi/qt5pi/include/QtCore/qendian.h \
		../../raspi/qt5pi/include/QtCore/qeventtransition.h \
		../../raspi/qt5pi/include/QtCore/qexception.h \
		../../raspi/qt5pi/include/QtCore/qfactoryinterface.h \
		../../raspi/qt5pi/include/QtCore/qfileselector.h \
		../../raspi/qt5pi/include/QtCore/QStringList \
		../../raspi/qt5pi/include/QtCore/qfilesystemwatcher.h \
		../../raspi/qt5pi/include/QtCore/qfinalstate.h \
		../../raspi/qt5pi/include/QtCore/qfuture.h \
		../../raspi/qt5pi/include/QtCore/qfutureinterface.h \
		../../raspi/qt5pi/include/QtCore/qrunnable.h \
		../../raspi/qt5pi/include/QtCore/qresultstore.h \
		../../raspi/qt5pi/include/QtCore/qfuturesynchronizer.h \
		../../raspi/qt5pi/include/QtCore/qfuturewatcher.h \
		../../raspi/qt5pi/include/QtCore/qhistorystate.h \
		../../raspi/qt5pi/include/QtCore/qidentityproxymodel.h \
		../../raspi/qt5pi/include/QtCore/qisenum.h \
		../../raspi/qt5pi/include/QtCore/qitemselectionmodel.h \
		../../raspi/qt5pi/include/QtCore/qjsonarray.h \
		../../raspi/qt5pi/include/QtCore/qjsonvalue.h \
		../../raspi/qt5pi/include/QtCore/qjsondocument.h \
		../../raspi/qt5pi/include/QtCore/qjsonobject.h \
		../../raspi/qt5pi/include/QtCore/qlibrary.h \
		../../raspi/qt5pi/include/QtCore/qlibraryinfo.h \
		../../raspi/qt5pi/include/QtCore/qversionnumber.h \
		../../raspi/qt5pi/include/QtCore/qlinkedlist.h \
		../../raspi/qt5pi/include/QtCore/qlockfile.h \
		../../raspi/qt5pi/include/QtCore/qloggingcategory.h \
		../../raspi/qt5pi/include/QtCore/qmath.h \
		../../raspi/qt5pi/include/QtCore/qmessageauthenticationcode.h \
		../../raspi/qt5pi/include/QtCore/qmetaobject.h \
		../../raspi/qt5pi/include/QtCore/qmimedata.h \
		../../raspi/qt5pi/include/QtCore/qmimedatabase.h \
		../../raspi/qt5pi/include/QtCore/qmimetype.h \
		../../raspi/qt5pi/include/QtCore/qobjectcleanuphandler.h \
		../../raspi/qt5pi/include/QtCore/qoperatingsystemversion.h \
		../../raspi/qt5pi/include/QtCore/qparallelanimationgroup.h \
		../../raspi/qt5pi/include/QtCore/qpauseanimation.h \
		../../raspi/qt5pi/include/QtCore/qplugin.h \
		../../raspi/qt5pi/include/QtCore/qpointer.h \
		../../raspi/qt5pi/include/QtCore/qpluginloader.h \
		../../raspi/qt5pi/include/QtCore/qpropertyanimation.h \
		../../raspi/qt5pi/include/QtCore/qvariantanimation.h \
		../../raspi/qt5pi/include/QtCore/qqueue.h \
		../../raspi/qt5pi/include/QtCore/qrandom.h \
		../../raspi/qt5pi/include/QtCore/qreadwritelock.h \
		../../raspi/qt5pi/include/QtCore/qregularexpression.h \
		../../raspi/qt5pi/include/QtCore/qresource.h \
		../../raspi/qt5pi/include/QtCore/qsavefile.h \
		../../raspi/qt5pi/include/QtCore/qscopedvaluerollback.h \
		../../raspi/qt5pi/include/QtCore/qsemaphore.h \
		../../raspi/qt5pi/include/QtCore/qsequentialanimationgroup.h \
		../../raspi/qt5pi/include/QtCore/qsettings.h \
		../../raspi/qt5pi/include/QtCore/qsharedmemory.h \
		../../raspi/qt5pi/include/QtCore/qsignalmapper.h \
		../../raspi/qt5pi/include/QtCore/qsignaltransition.h \
		../../raspi/qt5pi/include/QtCore/qsocketnotifier.h \
		../../raspi/qt5pi/include/QtCore/qsortfilterproxymodel.h \
		../../raspi/qt5pi/include/QtCore/qstack.h \
		../../raspi/qt5pi/include/QtCore/qstandardpaths.h \
		../../raspi/qt5pi/include/QtCore/qstate.h \
		../../raspi/qt5pi/include/QtCore/qstatemachine.h \
		../../raspi/qt5pi/include/QtCore/qstorageinfo.h \
		../../raspi/qt5pi/include/QtCore/qstringlistmodel.h \
		../../raspi/qt5pi/include/QtCore/qsystemsemaphore.h \
		../../raspi/qt5pi/include/QtCore/qtemporarydir.h \
		../../raspi/qt5pi/include/QtCore/QScopedPointer \
		../../raspi/qt5pi/include/QtCore/qtemporaryfile.h \
		../../raspi/qt5pi/include/QtCore/qtextboundaryfinder.h \
		../../raspi/qt5pi/include/QtCore/qtextcodec.h \
		../../raspi/qt5pi/include/QtCore/qthread.h \
		../../raspi/qt5pi/include/QtCore/qthreadpool.h \
		../../raspi/qt5pi/include/QtCore/qthreadstorage.h \
		../../raspi/qt5pi/include/QtCore/qtimeline.h \
		../../raspi/qt5pi/include/QtCore/qtimer.h \
		../../raspi/qt5pi/include/QtCore/qtimezone.h \
		../../raspi/qt5pi/include/QtCore/qtranslator.h \
		../../raspi/qt5pi/include/QtCore/qtypetraits.h \
		../../raspi/qt5pi/include/QtCore/quuid.h \
		../../raspi/qt5pi/include/QtCore/qwaitcondition.h \
		../../raspi/qt5pi/include/QtCore/qwineventnotifier.h \
		../../raspi/qt5pi/include/QtCore/qxmlstream.h \
		../../raspi/qt5pi/include/QtCore/qtcoreversion.h \
		../../raspi/qt5pi/include/QtSql/qtsqlglobal.h \
		../../raspi/qt5pi/include/QtSql/qsqldatabase.h \
		../../raspi/qt5pi/include/QtSql/qsqldriver.h \
		../../raspi/qt5pi/include/QtSql/qsqldriverplugin.h \
		../../raspi/qt5pi/include/QtSql/qsqlerror.h \
		../../raspi/qt5pi/include/QtSql/qsqlfield.h \
		../../raspi/qt5pi/include/QtSql/qsqlindex.h \
		../../raspi/qt5pi/include/QtSql/qsqlrecord.h \
		../../raspi/qt5pi/include/QtSql/qsqlquery.h \
		../../raspi/qt5pi/include/QtSql/qsqlquerymodel.h \
		../../raspi/qt5pi/include/QtSql/qsqlrelationaldelegate.h \
		../../raspi/qt5pi/include/QtWidgets/qitemdelegate.h \
		../../raspi/qt5pi/include/QtWidgets/qabstractitemdelegate.h \
		../../raspi/qt5pi/include/QtWidgets/qstyleoption.h \
		../../raspi/qt5pi/include/QtWidgets/qabstractspinbox.h \
		../../raspi/qt5pi/include/QtGui/qvalidator.h \
		../../raspi/qt5pi/include/QtWidgets/qslider.h \
		../../raspi/qt5pi/include/QtWidgets/qabstractslider.h \
		../../raspi/qt5pi/include/QtWidgets/qtabbar.h \
		../../raspi/qt5pi/include/QtWidgets/qrubberband.h \
		../../raspi/qt5pi/include/QtWidgets/qlistview.h \
		../../raspi/qt5pi/include/QtWidgets/qabstractitemview.h \
		../../raspi/qt5pi/include/QtWidgets/qabstractscrollarea.h \
		../../raspi/qt5pi/include/QtWidgets/qcombobox.h \
		../../raspi/qt5pi/include/QtSql/qsqlrelationaltablemodel.h \
		../../raspi/qt5pi/include/QtSql/qsqltablemodel.h \
		../../raspi/qt5pi/include/QtSql/qsqlresult.h \
		../../raspi/qt5pi/include/QtSql/qtsqlversion.h \
		../../raspi/qt5pi/include/QtSql/QSqlQuery \
		communication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frame.o frame.cpp

contact.o: contact.cpp contact.h \
		../../raspi/qt5pi/include/QtCore/QObject \
		../../raspi/qt5pi/include/QtCore/qobject.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../raspi/qt5pi/include/QtCore/qflags.h \
		../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../raspi/qt5pi/include/QtCore/qstring.h \
		../../raspi/qt5pi/include/QtCore/qchar.h \
		../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qstringview.h \
		../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../raspi/qt5pi/include/QtCore/qlist.h \
		../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../raspi/qt5pi/include/QtCore/qpair.h \
		../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../raspi/qt5pi/include/QtCore/QString
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contact.o contact.cpp

main.o: main.cpp ../../raspi/qt5pi/include/QtWidgets/QApplication \
		../../raspi/qt5pi/include/QtWidgets/qapplication.h \
		../../raspi/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../raspi/qt5pi/include/QtCore/qflags.h \
		../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../../raspi/qt5pi/include/QtWidgets/qtwidgets-config.h \
		../../raspi/qt5pi/include/QtCore/qcoreapplication.h \
		../../raspi/qt5pi/include/QtCore/qstring.h \
		../../raspi/qt5pi/include/QtCore/qchar.h \
		../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qstringview.h \
		../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../raspi/qt5pi/include/QtCore/qobject.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../raspi/qt5pi/include/QtCore/qlist.h \
		../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../raspi/qt5pi/include/QtCore/qpair.h \
		../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../raspi/qt5pi/include/QtCore/qeventloop.h \
		../../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../raspi/qt5pi/include/QtCore/qsize.h \
		../../raspi/qt5pi/include/QtGui/qcursor.h \
		../../raspi/qt5pi/include/QtWidgets/qdesktopwidget.h \
		../../raspi/qt5pi/include/QtWidgets/qwidget.h \
		../../raspi/qt5pi/include/QtCore/qmargins.h \
		../../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../../raspi/qt5pi/include/QtCore/qrect.h \
		../../raspi/qt5pi/include/QtGui/qpalette.h \
		../../raspi/qt5pi/include/QtGui/qcolor.h \
		../../raspi/qt5pi/include/QtGui/qrgb.h \
		../../raspi/qt5pi/include/QtGui/qrgba64.h \
		../../raspi/qt5pi/include/QtGui/qbrush.h \
		../../raspi/qt5pi/include/QtCore/qvector.h \
		../../raspi/qt5pi/include/QtGui/qmatrix.h \
		../../raspi/qt5pi/include/QtGui/qpolygon.h \
		../../raspi/qt5pi/include/QtGui/qregion.h \
		../../raspi/qt5pi/include/QtCore/qdatastream.h \
		../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../raspi/qt5pi/include/QtCore/qline.h \
		../../raspi/qt5pi/include/QtGui/qtransform.h \
		../../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../../raspi/qt5pi/include/QtGui/qimage.h \
		../../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../../raspi/qt5pi/include/QtGui/qpixmap.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../raspi/qt5pi/include/QtCore/qhash.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../raspi/qt5pi/include/QtGui/qfont.h \
		../../raspi/qt5pi/include/QtGui/qfontmetrics.h \
		../../raspi/qt5pi/include/QtGui/qfontinfo.h \
		../../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../../raspi/qt5pi/include/QtGui/qevent.h \
		../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../raspi/qt5pi/include/QtCore/qmap.h \
		../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../raspi/qt5pi/include/QtCore/qset.h \
		../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../raspi/qt5pi/include/QtCore/qurl.h \
		../../raspi/qt5pi/include/QtCore/qurlquery.h \
		../../raspi/qt5pi/include/QtCore/qfile.h \
		../../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../../raspi/qt5pi/include/QtGui/qvector2d.h \
		../../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../../raspi/qt5pi/include/QtGui/qguiapplication.h \
		../../raspi/qt5pi/include/QtGui/qinputmethod.h \
		../../raspi/qt5pi/include/QtWidgets/QStyle \
		../../raspi/qt5pi/include/QtWidgets/qstyle.h \
		../../raspi/qt5pi/include/QtGui/qicon.h \
		../../raspi/qt5pi/include/QtWidgets/QDesktopWidget \
		frame.h \
		../../raspi/qt5pi/include/QtWidgets/QMainWindow \
		../../raspi/qt5pi/include/QtWidgets/qmainwindow.h \
		../../raspi/qt5pi/include/QtWidgets/qtabwidget.h \
		../../raspi/qt5pi/include/QtWidgets/QGridLayout \
		../../raspi/qt5pi/include/QtWidgets/qgridlayout.h \
		../../raspi/qt5pi/include/QtWidgets/qlayout.h \
		../../raspi/qt5pi/include/QtWidgets/qlayoutitem.h \
		../../raspi/qt5pi/include/QtWidgets/qboxlayout.h \
		../../raspi/qt5pi/include/QtCore/QMapIterator \
		contact.h \
		../../raspi/qt5pi/include/QtCore/QObject \
		../../raspi/qt5pi/include/QtCore/QString \
		communication.h \
		../../raspi/qt5pi/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

communication.o: communication.cpp ../../raspi/qt5pi/include/QtSerialPort/QSerialPort \
		../../raspi/qt5pi/include/QtSerialPort/qserialport.h \
		../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../raspi/qt5pi/include/QtCore/qflags.h \
		../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../raspi/qt5pi/include/QtCore/qobject.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../raspi/qt5pi/include/QtCore/qstring.h \
		../../raspi/qt5pi/include/QtCore/qchar.h \
		../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qstringview.h \
		../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../raspi/qt5pi/include/QtCore/qlist.h \
		../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../raspi/qt5pi/include/QtCore/qpair.h \
		../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../raspi/qt5pi/include/QtSerialPort/qserialportglobal.h \
		../../raspi/qt5pi/include/QtSerialPort/QSerialPortInfo \
		../../raspi/qt5pi/include/QtSerialPort/qserialportinfo.h \
		communication.h \
		../../raspi/qt5pi/include/QtCore/QString \
		../../raspi/qt5pi/include/QtCore/QDebug \
		../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../raspi/qt5pi/include/QtCore/qhash.h \
		../../raspi/qt5pi/include/QtCore/qmap.h \
		../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../raspi/qt5pi/include/QtCore/qvector.h \
		../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../raspi/qt5pi/include/QtCore/qset.h \
		../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../raspi/qt5pi/include/QtCore/QByteArray
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o communication.o communication.cpp

moc_frame.o: moc_frame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frame.o moc_frame.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

